/**
 * Country name to ISO 3166-1 alpha-3 code mapping
 * Used for choropleth map coloring
 */

export const COUNTRY_ISO_CODES: Record<string, string> = {
  // Africa
  'Algeria': 'DZA',
  'Angola': 'AGO',
  'Benin': 'BEN',
  'Botswana': 'BWA',
  'Burkina Faso': 'BFA',
  'Burundi': 'BDI',
  'Cameroon': 'CMR',
  'Cape Verde': 'CPV',
  'Central African Republic': 'CAF',
  'Chad': 'TCD',
  'Comoros': 'COM',
  'Congo': 'COG',
  'Democratic Republic of the Congo': 'COD',
  'DRC': 'COD',
  'Djibouti': 'DJI',
  'Egypt': 'EGY',
  'Equatorial Guinea': 'GNQ',
  'Eritrea': 'ERI',
  'Eswatini': 'SWZ',
  'Ethiopia': 'ETH',
  'Gabon': 'GAB',
  'Gambia': 'GMB',
  'Ghana': 'GHA',
  'Guinea': 'GIN',
  'Guinea-Bissau': 'GNB',
  'Ivory Coast': 'CIV',
  "Côte d'Ivoire": 'CIV',
  'Kenya': 'KEN',
  'Lesotho': 'LSO',
  'Liberia': 'LBR',
  'Libya': 'LBY',
  'Madagascar': 'MDG',
  'Malawi': 'MWI',
  'Mali': 'MLI',
  'Mauritania': 'MRT',
  'Mauritius': 'MUS',
  'Morocco': 'MAR',
  'Mozambique': 'MOZ',
  'Namibia': 'NAM',
  'Niger': 'NER',
  'Nigeria': 'NGA',
  'Rwanda': 'RWA',
  'Sao Tome and Principe': 'STP',
  'Senegal': 'SEN',
  'Seychelles': 'SYC',
  'Sierra Leone': 'SLE',
  'Somalia': 'SOM',
  'South Africa': 'ZAF',
  'South Sudan': 'SSD',
  'Sudan': 'SDN',
  'Tanzania': 'TZA',
  'United Republic of Tanzania': 'TZA',
  'Togo': 'TGO',
  'Tunisia': 'TUN',
  'Uganda': 'UGA',
  'Zambia': 'ZMB',
  'Zimbabwe': 'ZWE',
  
  // Americas
  'Argentina': 'ARG',
  'Bahamas': 'BHS',
  'Barbados': 'BRB',
  'Belize': 'BLZ',
  'Bolivia': 'BOL',
  'Brazil': 'BRA',
  'Canada': 'CAN',
  'Chile': 'CHL',
  'Colombia': 'COL',
  'Costa Rica': 'CRI',
  'Cuba': 'CUB',
  'Dominican Republic': 'DOM',
  'Ecuador': 'ECU',
  'El Salvador': 'SLV',
  'Guatemala': 'GTM',
  'Guyana': 'GUY',
  'Haiti': 'HTI',
  'Honduras': 'HND',
  'Jamaica': 'JAM',
  'Mexico': 'MEX',
  'Nicaragua': 'NIC',
  'Panama': 'PAN',
  'Paraguay': 'PRY',
  'Peru': 'PER',
  'Suriname': 'SUR',
  'Trinidad and Tobago': 'TTO',
  'United States': 'USA',
  'United States of America': 'USA',
  'Uruguay': 'URY',
  'Venezuela': 'VEN',
  
  // Asia
  'Afghanistan': 'AFG',
  'Armenia': 'ARM',
  'Azerbaijan': 'AZE',
  'Bahrain': 'BHR',
  'Bangladesh': 'BGD',
  'Bhutan': 'BTN',
  'Brunei': 'BRN',
  'Cambodia': 'KHM',
  'China': 'CHN',
  "People's Republic of China": 'CHN',
  'Cyprus': 'CYP',
  'Georgia': 'GEO',
  'India': 'IND',
  'Indonesia': 'IDN',
  'Iran': 'IRN',
  'Iraq': 'IRQ',
  'Israel': 'ISR',
  'Japan': 'JPN',
  'Jordan': 'JOR',
  'Kazakhstan': 'KAZ',
  'Kuwait': 'KWT',
  'Kyrgyzstan': 'KGZ',
  'Laos': 'LAO',
  "Lao People's Democratic Republic": 'LAO',
  'Lebanon': 'LBN',
  'Malaysia': 'MYS',
  'Maldives': 'MDV',
  'Mongolia': 'MNG',
  'Myanmar': 'MMR',
  'Nepal': 'NPL',
  'North Korea': 'PRK',
  'Oman': 'OMN',
  'Pakistan': 'PAK',
  'Palestine': 'PSE',
  'State of Palestine': 'PSE',
  'Philippines': 'PHL',
  'Qatar': 'QAT',
  'Saudi Arabia': 'SAU',
  'Singapore': 'SGP',
  'South Korea': 'KOR',
  'Republic of Korea': 'KOR',
  'Sri Lanka': 'LKA',
  'Syria': 'SYR',
  'Syrian Arab Republic': 'SYR',
  'Taiwan': 'TWN',
  'Tajikistan': 'TJK',
  'Thailand': 'THA',
  'Timor-Leste': 'TLS',
  'Turkey': 'TUR',
  'Türkiye': 'TUR',
  'Turkmenistan': 'TKM',
  'United Arab Emirates': 'ARE',
  'UAE': 'ARE',
  'Uzbekistan': 'UZB',
  'Vietnam': 'VNM',
  'Viet Nam': 'VNM',
  'Yemen': 'YEM',
  
  // Europe
  'Albania': 'ALB',
  'Andorra': 'AND',
  'Austria': 'AUT',
  'Belarus': 'BLR',
  'Belgium': 'BEL',
  'Bosnia and Herzegovina': 'BIH',
  'Bulgaria': 'BGR',
  'Croatia': 'HRV',
  'Czech Republic': 'CZE',
  'Czechia': 'CZE',
  'Denmark': 'DNK',
  'Estonia': 'EST',
  'Finland': 'FIN',
  'France': 'FRA',
  'Germany': 'DEU',
  'Greece': 'GRC',
  'Hungary': 'HUN',
  'Iceland': 'ISL',
  'Ireland': 'IRL',
  'Italy': 'ITA',
  'Kosovo': 'XKX',
  'Latvia': 'LVA',
  'Liechtenstein': 'LIE',
  'Lithuania': 'LTU',
  'Luxembourg': 'LUX',
  'Malta': 'MLT',
  'Moldova': 'MDA',
  'Republic of Moldova': 'MDA',
  'Monaco': 'MCO',
  'Montenegro': 'MNE',
  'Netherlands': 'NLD',
  'North Macedonia': 'MKD',
  'Norway': 'NOR',
  'Poland': 'POL',
  'Portugal': 'PRT',
  'Romania': 'ROU',
  'Russia': 'RUS',
  'Russian Federation': 'RUS',
  'San Marino': 'SMR',
  'Serbia': 'SRB',
  'Slovakia': 'SVK',
  'Slovenia': 'SVN',
  'Spain': 'ESP',
  'Sweden': 'SWE',
  'Switzerland': 'CHE',
  'Ukraine': 'UKR',
  'United Kingdom': 'GBR',
  'Vatican City': 'VAT',
  
  // Oceania
  'Australia': 'AUS',
  'Fiji': 'FJI',
  'Kiribati': 'KIR',
  'Marshall Islands': 'MHL',
  'Micronesia': 'FSM',
  'Nauru': 'NRU',
  'New Zealand': 'NZL',
  'Palau': 'PLW',
  'Papua New Guinea': 'PNG',
  'Samoa': 'WSM',
  'Solomon Islands': 'SLB',
  'Tonga': 'TON',
  'Tuvalu': 'TUV',
  'Vanuatu': 'VUT',
};

/**
 * Get ISO code from country name (case-insensitive)
 */
export function getCountryIsoCode(countryName: string): string | null {
  // Direct lookup
  if (COUNTRY_ISO_CODES[countryName]) {
    return COUNTRY_ISO_CODES[countryName];
  }
  
  // Case-insensitive lookup
  const normalized = countryName.trim();
  for (const [name, code] of Object.entries(COUNTRY_ISO_CODES)) {
    if (name.toLowerCase() === normalized.toLowerCase()) {
      return code;
    }
  }
  
  return null;
}

/**
 * ISO code to country name mapping (reverse lookup)
 */
export const ISO_TO_COUNTRY: Record<string, string> = Object.entries(COUNTRY_ISO_CODES)
  .reduce((acc, [name, code]) => {
    if (!acc[code]) {
      acc[code] = name;
    }
    return acc;
  }, {} as Record<string, string>);


