/**
 * PDF Generator Service
 * Assembles the final PDF report (simplified version)
 */

import * as fs from 'fs';
import * as path from 'path';
import {
  ReportData,
  ReportMetadata,
  AgencyReportMetrics,
  BenchmarkMetrics,
  CompetitiveIntelligence,
  ReportInsights,
  StrategicRecommendation,
  AGENCY_COLORS
} from '../../types/reports';
import { ReportCharts, ChartGenerator } from './ChartGenerator';

// PDF document definition types for pdfmake
interface PDFContent {
  text?: string;
  style?: string | string[];
  columns?: PDFContent[];
  stack?: PDFContent[];
  table?: {
    headerRows?: number;
    widths?: (string | number)[];
    body: PDFContent[][];
  };
  layout?: string | object;
  margin?: number[];
  image?: string;
  width?: number | string;
  height?: number;
  alignment?: string;
  pageBreak?: string;
  fillColor?: string;
  color?: string;
  bold?: boolean;
  fontSize?: number;
  ul?: (string | PDFContent)[];
}

export class PDFGenerator {
  private chartGenerator: ChartGenerator;
  private publicDir: string;

  constructor(publicDir: string = path.join(__dirname, '../../../../public')) {
    this.chartGenerator = new ChartGenerator();
    this.publicDir = publicDir;
  }

  /**
   * Generate the complete PDF document definition
   */
  generatePDFDocument(reportData: ReportData): object {
    const {
      metadata,
      agencyMetrics,
      benchmarks,
      competitiveIntelligence,
      insights,
      recommendations
    } = reportData;

    const charts = this.chartGenerator.generateAllCharts(
      agencyMetrics,
      benchmarks,
      competitiveIntelligence
    );

    const agencyColor = AGENCY_COLORS[agencyMetrics.agencyInfo.shortName] || AGENCY_COLORS['default'] || '#0468B1';

    return {
      pageSize: 'A4',
      pageMargins: [40, 60, 40, 60],
      
      header: (currentPage: number, pageCount: number) => {
        if (currentPage === 1) return null;
        return {
          columns: [
            { 
              text: `${metadata.agency} HR Intelligence Report`, 
              margin: [40, 20, 0, 0],
              fontSize: 9,
              color: '#666666'
            },
            { 
              text: `Page ${currentPage} of ${pageCount}`, 
              alignment: 'right',
              margin: [0, 20, 40, 0],
              fontSize: 9,
              color: '#666666'
            }
          ]
        };
      },

      footer: {
        columns: [
          { 
            text: 'Generated by UN Jobs Analytics Platform', 
            alignment: 'center',
            margin: [0, 20, 0, 0],
            fontSize: 8,
            color: '#999999'
          }
        ]
      },

      content: [
        // Cover Page
        ...this.generateCoverPage(metadata, agencyMetrics, agencyColor),
        
        // Executive Summary
        { text: '', pageBreak: 'after' },
        ...this.generateExecutiveSummary(agencyMetrics, benchmarks, insights),
        
        // Section 1: Hiring Activity
        { text: '', pageBreak: 'after' },
        ...this.generateHiringActivitySection(agencyMetrics, benchmarks),
        
        // Section 2: Workforce Composition
        { text: '', pageBreak: 'after' },
        ...this.generateWorkforceSection(agencyMetrics),
        
        // Section 3: Strategic Insights
        { text: '', pageBreak: 'after' },
        ...this.generateStrategicSection(insights, recommendations)
      ],

      styles: {
        header: { fontSize: 24, bold: true, color: agencyColor },
        subheader: { fontSize: 16, bold: true, margin: [0, 15, 0, 5] },
        sectionTitle: { fontSize: 14, bold: true, color: agencyColor, margin: [0, 10, 0, 5] },
        body: { fontSize: 10, lineHeight: 1.4 },
        metric: { fontSize: 24, bold: true, color: agencyColor },
        metricLabel: { fontSize: 9, color: '#666666' },
        tableHeader: { fontSize: 10, bold: true, fillColor: '#f5f5f5' },
        tableCell: { fontSize: 9 }
      },

      defaultStyle: {
        fontSize: 10
      }
    };
  }

  private generateCoverPage(
    metadata: ReportMetadata,
    metrics: AgencyReportMetrics,
    agencyColor: string
  ): PDFContent[] {
    return [
      { text: '', margin: [0, 100, 0, 0] },
      {
        text: metrics.agencyInfo.longName || metrics.agencyInfo.shortName,
        style: 'header',
        alignment: 'center'
      },
      { text: '', margin: [0, 20, 0, 0] },
      {
        text: 'Monthly HR Intelligence Report',
        fontSize: 18,
        alignment: 'center',
        color: '#444444'
      },
      { text: '', margin: [0, 30, 0, 0] },
      {
        text: metadata.reportPeriod.displayPeriod,
        fontSize: 14,
        alignment: 'center',
        color: '#666666'
      },
      { text: '', margin: [0, 60, 0, 0] },
      {
        columns: [
          {
            width: '*',
            stack: [
              { text: 'Total Positions', style: 'metricLabel', alignment: 'center' },
              { text: metrics.volumeMetrics.totalPostings.toString(), style: 'metric', alignment: 'center' }
            ]
          },
          {
            width: '*',
            stack: [
              { text: 'Active Openings', style: 'metricLabel', alignment: 'center' },
              { text: metrics.volumeMetrics.activePostings.toString(), style: 'metric', alignment: 'center' }
            ]
          },
          {
            width: '*',
            stack: [
              { text: 'Countries', style: 'metricLabel', alignment: 'center' },
              { text: metrics.geographicAnalysis.regionDistribution.length.toString(), style: 'metric', alignment: 'center' }
            ]
          }
        ]
      },
      { text: '', margin: [0, 80, 0, 0] },
      {
        text: `Generated: ${new Date(metadata.generatedAt).toLocaleDateString('en-US', { 
          year: 'numeric', month: 'long', day: 'numeric' 
        })}`,
        fontSize: 9,
        alignment: 'center',
        color: '#999999'
      }
    ];
  }

  private generateExecutiveSummary(
    metrics: AgencyReportMetrics,
    benchmarks: BenchmarkMetrics,
    insights: ReportInsights
  ): PDFContent[] {
    const content: PDFContent[] = [
      { text: 'Executive Summary', style: 'header', margin: [0, 0, 0, 20] }
    ];

    // Key metrics grid
    content.push({
      columns: [
        {
          width: '25%',
          stack: [
            { text: 'Total Postings', style: 'metricLabel' },
            { text: metrics.volumeMetrics.totalPostings.toLocaleString(), style: 'metric' },
            { 
              text: `${metrics.volumeMetrics.monthOverMonthChange >= 0 ? '+' : ''}${metrics.volumeMetrics.monthOverMonthChange.toFixed(0)}% vs prev`,
              fontSize: 9,
              color: metrics.volumeMetrics.monthOverMonthChange >= 0 ? '#28a745' : '#dc3545'
            }
          ]
        },
        {
          width: '25%',
          stack: [
            { text: 'Active Positions', style: 'metricLabel' },
            { text: metrics.volumeMetrics.activePostings.toLocaleString(), style: 'metric' }
          ]
        },
        {
          width: '25%',
          stack: [
            { text: 'Avg Application Window', style: 'metricLabel' },
            { text: `${metrics.applicationMetrics.avgApplicationWindow.toFixed(0)} days`, style: 'metric' }
          ]
        },
        {
          width: '25%',
          stack: [
            { text: 'Market Avg', style: 'metricLabel' },
            { text: `${benchmarks.marketAverages.avgApplicationWindow.toFixed(0)} days`, fontSize: 14, color: '#666' }
          ]
        }
      ],
      margin: [0, 0, 0, 30]
    } as PDFContent);

    // Key insights
    content.push({ text: 'Key Insights', style: 'sectionTitle' });
    
    const allInsights = [
      ...insights.volumeInsights.slice(0, 2),
      ...insights.competitiveInsights.slice(0, 2),
      ...insights.strategicInsights.slice(0, 2)
    ];

    content.push({
      ul: allInsights.map(insight => ({
        text: `${insight.title}: ${insight.description}`,
        margin: [0, 3, 0, 3] as number[]
      }))
    });

    return content;
  }

  private generateHiringActivitySection(
    metrics: AgencyReportMetrics,
    benchmarks: BenchmarkMetrics
  ): PDFContent[] {
    const content: PDFContent[] = [
      { text: 'Section 1: Hiring Activity Analysis', style: 'header', margin: [0, 0, 0, 20] }
    ];

    // Volume metrics
    content.push({ text: 'Position Volume', style: 'sectionTitle' });
    content.push({
      table: {
        widths: ['*', '*', '*', '*'],
        body: [
          [
            { text: 'Metric', style: 'tableHeader' },
            { text: 'This Period', style: 'tableHeader' },
            { text: 'Previous Period', style: 'tableHeader' },
            { text: 'Change', style: 'tableHeader' }
          ],
          [
            'Total Postings',
            metrics.volumeMetrics.totalPostings.toString(),
            metrics.volumeMetrics.previousMonthPostings.toString(),
            `${metrics.volumeMetrics.monthOverMonthChange >= 0 ? '+' : ''}${metrics.volumeMetrics.monthOverMonthChange.toFixed(0)}%`
          ],
          [
            'Active Positions',
            metrics.volumeMetrics.activePostings.toString(),
            '-',
            '-'
          ],
          [
            'Closing Soon (≤14 days)',
            metrics.volumeMetrics.closingSoonPostings.toString(),
            '-',
            '-'
          ]
        ]
      },
      layout: 'lightHorizontalLines',
      margin: [0, 0, 0, 20]
    } as PDFContent);

    // Application window
    content.push({ text: 'Application Windows', style: 'sectionTitle' });
    content.push({
      table: {
        widths: ['*', '*', '*'],
        body: [
          [
            { text: 'Metric', style: 'tableHeader' },
            { text: 'Your Agency', style: 'tableHeader' },
            { text: 'Market Average', style: 'tableHeader' }
          ],
          [
            'Avg Application Window',
            `${metrics.applicationMetrics.avgApplicationWindow.toFixed(0)} days`,
            `${benchmarks.marketAverages.avgApplicationWindow.toFixed(0)} days`
          ],
          [
            'Median Window',
            `${metrics.applicationMetrics.medianApplicationWindow} days`,
            '-'
          ],
          [
            'Urgent Positions',
            `${metrics.applicationMetrics.urgentPositionsCount} (${metrics.applicationMetrics.urgentPositionsPercentage.toFixed(0)}%)`,
            '-'
          ]
        ]
      },
      layout: 'lightHorizontalLines',
      margin: [0, 0, 0, 20]
    } as PDFContent);

    return content;
  }

  private generateWorkforceSection(metrics: AgencyReportMetrics): PDFContent[] {
    const content: PDFContent[] = [
      { text: 'Section 2: Workforce Composition', style: 'header', margin: [0, 0, 0, 20] }
    ];

    // Staff type breakdown
    content.push({ text: 'Staff Type Distribution', style: 'sectionTitle' });
    const staffTypes = metrics.workforceComposition.staffTypeBreakdown;
    content.push({
      table: {
        widths: ['*', '*', '*'],
        body: [
          [
            { text: 'Staff Type', style: 'tableHeader' },
            { text: 'Count', style: 'tableHeader' },
            { text: 'Percentage', style: 'tableHeader' }
          ],
          ['International', staffTypes.international.count.toString(), `${staffTypes.international.percentage.toFixed(1)}%`],
          ['National', staffTypes.national.count.toString(), `${staffTypes.national.percentage.toFixed(1)}%`],
          ['Consultant', staffTypes.consultant.count.toString(), `${staffTypes.consultant.percentage.toFixed(1)}%`],
          ['Intern', staffTypes.intern.count.toString(), `${staffTypes.intern.percentage.toFixed(1)}%`],
          ['Other', staffTypes.other.count.toString(), `${staffTypes.other.percentage.toFixed(1)}%`]
        ]
      },
      layout: 'lightHorizontalLines',
      margin: [0, 0, 0, 20]
    } as PDFContent);

    // Grade distribution
    content.push({ text: 'Top Grade Levels', style: 'sectionTitle' });
    const topGrades = metrics.workforceComposition.gradeDistribution.slice(0, 10);
    content.push({
      table: {
        widths: ['*', '*', '*'],
        body: [
          [
            { text: 'Grade', style: 'tableHeader' },
            { text: 'Count', style: 'tableHeader' },
            { text: 'Percentage', style: 'tableHeader' }
          ],
          ...topGrades.map(g => [g.grade, g.count.toString(), `${g.percentage.toFixed(1)}%`])
        ]
      },
      layout: 'lightHorizontalLines',
      margin: [0, 0, 0, 20]
    } as PDFContent);

    // Geographic distribution
    content.push({ text: 'Top Duty Stations', style: 'sectionTitle' });
    const topStations = metrics.geographicAnalysis.topDutyStations.slice(0, 10);
    content.push({
      table: {
        widths: ['*', '*', '*'],
        body: [
          [
            { text: 'Location', style: 'tableHeader' },
            { text: 'Count', style: 'tableHeader' },
            { text: 'Percentage', style: 'tableHeader' }
          ],
          ...topStations.map(s => [s.station, s.count.toString(), `${s.percentage.toFixed(1)}%`])
        ]
      },
      layout: 'lightHorizontalLines',
      margin: [0, 0, 0, 20]
    } as PDFContent);

    return content;
  }

  private generateStrategicSection(
    insights: ReportInsights,
    recommendations: StrategicRecommendation[]
  ): PDFContent[] {
    const content: PDFContent[] = [
      { text: 'Section 3: Strategic Insights & Recommendations', style: 'header', margin: [0, 0, 0, 20] }
    ];

    // Recommendations
    content.push({ text: 'Strategic Recommendations', style: 'sectionTitle' });
    
    recommendations.forEach((rec, index) => {
      content.push({
        stack: [
          {
            text: `${index + 1}. ${rec.recommendation}`,
            bold: true,
            margin: [0, 10, 0, 5]
          },
          {
            text: `Priority: ${rec.priority.toUpperCase()}`,
            fontSize: 9,
            color: rec.priority === 'high' ? '#dc3545' : rec.priority === 'medium' ? '#ffc107' : '#28a745'
          },
          {
            text: rec.rationale,
            margin: [0, 5, 0, 0],
            style: 'body'
          },
          {
            text: `Expected Impact: ${rec.impact}`,
            fontSize: 9,
            color: '#666666',
            margin: [0, 5, 0, 0]
          }
        ],
        margin: [0, 0, 0, 15]
      } as PDFContent);
    });

    return content;
  }

  /**
   * Save the PDF definition to a JSON file (for debugging)
   */
  saveDefinition(reportData: ReportData, outputPath: string): void {
    const definition = this.generatePDFDocument(reportData);
    fs.writeFileSync(outputPath, JSON.stringify(definition, null, 2));
  }
}

export default PDFGenerator;
